# Generated by Django 4.1.4 on 2022-12-21 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('patronymic_name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('university', models.CharField(blank=True, max_length=100)),
                ('university_faculty', models.CharField(blank=True, max_length=100)),
                ('university_specitality', models.CharField(blank=True, max_length=100)),
                ('university_course', models.CharField(blank=True, choices=[('2 курс', '2 курс'), ('3 курс', '3 курс')], max_length=100)),
                ('school_program', models.CharField(blank=True, choices=[('ONE ОДИН', 'ONE ОДИН'), ('TWO ОДИН', 'TWO ОДИН')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
